window.SENTINEL_SAMPLE_EVENTS = [
  {
    timestamp: "2026-05-08T08:05:11-05:00",
    source: "identity",
    event_type: "auth.failure",
    user: "maya.patel",
    host: "okta",
    src_ip: "185.244.25.44",
    country: "RU",
    message: "Failed SSO login for maya.patel from unfamiliar ASN",
    severity: "medium"
  },
  {
    timestamp: "2026-05-08T08:06:02-05:00",
    source: "identity",
    event_type: "auth.failure",
    user: "maya.patel",
    host: "okta",
    src_ip: "185.244.25.44",
    country: "RU",
    message: "Failed SSO login for maya.patel from unfamiliar ASN",
    severity: "medium"
  },
  {
    timestamp: "2026-05-08T08:07:21-05:00",
    source: "identity",
    event_type: "auth.failure",
    user: "maya.patel",
    host: "okta",
    src_ip: "185.244.25.44",
    country: "RU",
    message: "Failed SSO login for maya.patel from unfamiliar ASN",
    severity: "medium"
  },
  {
    timestamp: "2026-05-08T08:12:33-05:00",
    source: "identity",
    event_type: "auth.success",
    user: "maya.patel",
    host: "okta",
    src_ip: "185.244.25.44",
    country: "RU",
    message: "Successful SSO login after multiple failures",
    severity: "high"
  },
  {
    timestamp: "2026-05-08T08:18:48-05:00",
    source: "cloud",
    event_type: "privilege.change",
    user: "maya.patel",
    host: "aws-iam",
    src_ip: "185.244.25.44",
    country: "RU",
    message: "User added to AdminAccess break-glass group",
    severity: "critical"
  },
  {
    timestamp: "2026-05-08T08:23:02-05:00",
    source: "endpoint",
    event_type: "process.start",
    user: "maya.patel",
    host: "FIN-LAPTOP-17",
    process: "powershell.exe",
    command: "powershell -enc SQBFAFgAIAAoAGcAdwBtAGkAIAB3AGkAbgAzADIAXwBwAHIAbwBjAGUAcwBzACkA",
    src_ip: "10.42.6.17",
    country: "US",
    message: "Encoded PowerShell command spawned by office document",
    severity: "critical"
  },
  {
    timestamp: "2026-05-08T08:24:16-05:00",
    source: "endpoint",
    event_type: "credential.access",
    user: "maya.patel",
    host: "FIN-LAPTOP-17",
    process: "rundll32.exe",
    command: "rundll32.exe comsvcs.dll, MiniDump 684 lsass.dmp full",
    src_ip: "10.42.6.17",
    country: "US",
    message: "Suspicious memory dump attempt against LSASS",
    severity: "critical"
  },
  {
    timestamp: "2026-05-08T08:29:55-05:00",
    source: "network",
    event_type: "dns.query",
    user: "maya.patel",
    host: "FIN-LAPTOP-17",
    src_ip: "10.42.6.17",
    dest: "cdn-update-cloudsync.net",
    bytes_out: 128,
    message: "High entropy DNS query to newly observed domain",
    severity: "high"
  },
  {
    timestamp: "2026-05-08T08:35:55-05:00",
    source: "network",
    event_type: "dns.query",
    user: "maya.patel",
    host: "FIN-LAPTOP-17",
    src_ip: "10.42.6.17",
    dest: "cdn-update-cloudsync.net",
    bytes_out: 144,
    message: "Repeated DNS query interval suggests beaconing",
    severity: "high"
  },
  {
    timestamp: "2026-05-08T08:41:56-05:00",
    source: "network",
    event_type: "dns.query",
    user: "maya.patel",
    host: "FIN-LAPTOP-17",
    src_ip: "10.42.6.17",
    dest: "cdn-update-cloudsync.net",
    bytes_out: 139,
    message: "Repeated DNS query interval suggests beaconing",
    severity: "high"
  },
  {
    timestamp: "2026-05-08T08:50:13-05:00",
    source: "cloud",
    event_type: "data.access",
    user: "maya.patel",
    host: "aws-s3",
    src_ip: "185.244.25.44",
    country: "RU",
    object: "finance-q2-payroll.csv",
    bytes_out: 844560000,
    message: "Large download from restricted finance bucket",
    severity: "critical"
  },
  {
    timestamp: "2026-05-08T09:03:17-05:00",
    source: "network",
    event_type: "egress.spike",
    user: "maya.patel",
    host: "FIN-LAPTOP-17",
    src_ip: "10.42.6.17",
    dest: "198.51.100.77",
    bytes_out: 508320000,
    message: "Outbound transfer volume exceeds host baseline by 8.2x",
    severity: "critical"
  },
  {
    timestamp: "2026-05-08T09:15:44-05:00",
    source: "identity",
    event_type: "auth.success",
    user: "diego.reyes",
    host: "okta",
    src_ip: "73.18.48.2",
    country: "US",
    message: "Normal SSO login from trusted device",
    severity: "low"
  },
  {
    timestamp: "2026-05-08T09:24:20-05:00",
    source: "endpoint",
    event_type: "process.start",
    user: "diego.reyes",
    host: "ENG-MAC-04",
    process: "zsh",
    command: "git pull origin main",
    src_ip: "10.42.10.44",
    country: "US",
    message: "Developer shell command from managed workstation",
    severity: "low"
  },
  {
    timestamp: "2026-05-08T09:31:09-05:00",
    source: "cloud",
    event_type: "config.change",
    user: "service-ci",
    host: "gcp-firewall",
    src_ip: "10.42.2.9",
    country: "US",
    message: "Firewall rule opened port 22 to 0.0.0.0/0 for 20 minutes",
    severity: "high"
  }
];
